# Generated by Django 4.0.5 on 2022-06-13 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import review.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0004_rename_profile_photo_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to=review.models.user_directory_path, verbose_name='Picture')),
                ('description', models.TextField(max_length=300, verbose_name='Caption')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
