# Generated by Django 4.0.5 on 2022-06-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=5, editable=False, primary_key=True, serialize=False),
        ),
    ]
