# Generated by Django 4.0.5 on 2022-06-14 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_review_project_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='design',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='usability',
            field=models.SmallIntegerField(),
        ),
    ]
