# Generated by Django 4.0.5 on 2022-06-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_alter_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='project',
        ),
    ]
